"""Storage adapter interface."""

from typing import Protocol, List, Optional

from app.domain.base import EntityId
from app.domain.agent import Agent
from app.domain.scheduled_task import ScheduledTask
from app.domain.skill import Skill, SkillFile
from app.domain.tool import Tool
from app.domain.model_config import ModelConfig
from app.domain.feedback import FeedbackEvent
from app.domain.user import User
from app.domain.log import LogEntry


class StorageAdapter(Protocol):
    """Storage adapter protocol.

    All storage implementations must implement this interface.
    """

    # Agent operations
    async def save_agent(self, agent: Agent) -> None: ...
    async def get_agent(self, id: str) -> Optional[Agent]: ...
    async def list_agents(self, user_id: str, offset: int = 0, limit: int = 100) -> List[Agent]: ...
    async def delete_agent(self, id: str) -> None: ...

    # Skill operations
    async def save_skill(self, skill: Skill) -> None: ...
    async def get_skill(self, id: str) -> Optional[Skill]: ...
    async def list_skills(self, user_id: str, offset: int = 0, limit: int = 100) -> List[Skill]: ...
    async def delete_skill(self, id: str) -> None: ...
    async def save_skill_file(self, skill_id: str, filename: str, content: bytes) -> None: ...
    async def get_skill_file(self, skill_id: str, filename: str) -> Optional[bytes]: ...
    async def list_skill_files(self, skill_id: str) -> List[str]: ...
    async def delete_skill_file(self, skill_id: str, filename: str) -> None: ...

    # Feedback operations
    async def save_feedback(self, feedback: FeedbackEvent) -> None: ...
    async def get_feedback(self, id: str) -> Optional[FeedbackEvent]: ...
    async def list_feedback(self, skill_id: Optional[str] = None, offset: int = 0, limit: int = 100) -> List[FeedbackEvent]: ...

    # Tool operations
    async def save_tool(self, tool: Tool) -> None: ...
    async def get_tool(self, id: str) -> Optional[Tool]: ...
    async def list_tools(self, user_id: str) -> List[Tool]: ...
    async def delete_tool(self, id: str) -> None: ...

    # ModelConfig operations
    async def save_model_config(self, config: ModelConfig) -> None: ...
    async def get_model_config(self, id: str) -> Optional[ModelConfig]: ...
    async def list_model_configs(self, user_id: str) -> List[ModelConfig]: ...
    async def delete_model_config(self, id: str) -> None: ...

    # User operations
    async def save_user(self, user: User) -> None: ...
    async def get_user(self, id: str) -> Optional[User]: ...
    async def get_user_by_username(self, username: str) -> Optional[User]: ...
    async def get_user_by_email(self, email: str) -> Optional[User]: ...
    async def delete_user(self, id: str) -> None: ...

    # ScheduledTask operations
    async def save_scheduled_task(self, task: ScheduledTask) -> None: ...
    async def get_scheduled_task(self, id: str) -> Optional[ScheduledTask]: ...
    async def list_scheduled_tasks(self, user_id: EntityId, offset: int = 0, limit: int = 100) -> List[ScheduledTask]: ...
    async def delete_scheduled_task(self, id: str) -> None: ...

    # Log operations
    async def save_log(self, entry: LogEntry) -> None: ...
    async def query_logs(
        self,
        agent_id: str | None = None,
        session_id: str | None = None,
        action_type: str | None = None,
        tool_name: str | None = None,
        offset: int = 0,
        limit: int = 100,
    ) -> List[LogEntry]: ...
